# Generated by Django 4.2 on 2023-04-20 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_fitnessreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fitnessreport',
            name='exercise_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fitnessreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fitnessreport',
            name='jogging_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fitnessreport',
            name='running_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
