# Generated by Django 4.2 on 2023-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_fitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='exercise_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='jogging_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='running_time',
            field=models.DateTimeField(),
        ),
    ]
